### ISSUE TITLE
Transparent background?

### ISSUE THREAD

**Issue by EDIflyer** [Eonasdan/fa6-stream-deck-icon-pack-generator#1]
First of all - thanks so much for doing this, I love FontAwesome icons, great to have them on Stream Deck!

I notice though that the free ones at https://apps.elgato.com/icons/com.fortawsome.solid.free seem to all have a dark blue background which causes the button to glow more than the standard Elgato ones - do you know if there's an easy fix to make them have fully transparent backgrounds?

![image](https://user-images.githubusercontent.com/13610277/211399882-3ea9a4d3-b845-4e5a-9140-b88c1e95c096.png)

Thanks again for creating this!

**Comment by Eonasdan** [comment]
Thanks!

If you want to customize the background color you can set [this option](https://github.com/Eonasdan/fa6-stream-deck-icon-pack-generator/blob/main/index.js#L23). It looks like canvas supports 8 character hex so you could provide an alpha channel.

I actually used a color picker tool to grab the background color from the default buttons so that's why they are that color.

Let me know if that helps!

P.S. I have a [Ko-fi](https://ko-fi.com/eonasdan) if you're feeling generous :)
